# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Caijun's Blog
subtitle: ""
description: ""
keywords:
author: Caijun
language: en
timezone: ""

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://caijun0409.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: redefine

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Caijun0409/Caijun0409.github.io.git
  branch: main

theme_config:
  # 1. 基本信息 (对应左上角和页脚)
  info:
    title: 俊俊的个人博客
    subtitle: Redefine Your Hexo Journey.
    author: Caijun
    url: https://caijun0409.github.io

  # 2. 颜色设置
  colors:
    primary: "#A31F34"
    default_mode: light

  # 3. 首页大图与标题 (Home Banner)
  home_banner:
    enable: true
    style: fixed
    image:
      light: /images/banner.jpg # 确保 source/images/ 下有 banner.jpg
      dark: /images/banner.jpg
    title: Caijun的记录博客
    subtitle:
      text:
        - 技术
        - 阅读
        - 记录
        - 学习
      typing_speed: 100
      loop: true
    text_style:
      title_size: 2.8rem
      subtitle_size: 1.5rem

  # 4. 导航栏 (Navbar)
  navbar:
    auto_hide: false
    color:
      left: "#f78736"
      right: "#367df7"
      transparency: 35
    links:
      Home:
        path: /
        icon: fa-regular fa-house
      Archives:
        path: /archives
        icon: fa-regular fa-archive

  # 5. 页脚设置 (Footer)
  footer:
    runtime: true
    start: 2025/11/19 20:36:14
    statistics: true
    icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'

  # 6. 文章样式 (Article)
  articles:
    style:
      font_size: 16px
      line_height: 1.5
      image_border_radius: 14px
    word_count:
      enable: true
      count: true
      min2read: true

  # 7. 默认图片设置
  defaults:
    avatar: /images/avatar.jpg
